### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by blutz** [dailybruin/meow#8]
- [x] Handle errors with sendposts (and store them properly). For now, just keep trying to send each post until it sends. See #4 for later plans
- [x] Make a frontend UI
- [x] Put test credentials in readme
- [x] Upload to a server and configure cron
- [x] Revoke test account credentials
- [x] Create installation instructions
- [ ] Make open-source
